site_name: 分形圆舞曲
site_url: https://FractalWaltz.github.io/
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
plugins:
  - search
  - blog
  # - awesome-nav
nav:
  - Home: index.md
  - Blog:
      - blog/index.md
